### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by nicholas477** [nicholas477/VC#1]
# Crap to do now:

- [ ] Allow joining by steam session ID
- [ ] Fix boat camera (make it lock to 4 directions)
- [ ] Add sounds (wind, water, footsteps)?
- [x] Day/night cycle
- [ ] Fix boat getting stuck on shit
- [ ] Add movement animations
- [ ] Make a proper sailing movement controller
- [ ] Add chop down trees
- [ ] Fix boat disappearing when player DCs
- [ ] Add "Press E to interact" UI widget
- [ ] add houses
- [ ] add mountains
- [ ] Add tileset for terrain
